### ISSUE TITLE
Add idempotency_level to health check schema

### ISSUE THREAD

**Issue by akshayjshah** [grpc/grpc-proto#127]
What do you think of adding [`idempotency_level`](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/descriptor.proto#L815) options to the [health check schema](https://github.com/grpc/grpc-proto/blob/master/grpc/health/v1/health.proto)? The most appropriate level seems to be `NO_SIDE_EFFECTS`.

Even though gRPC always uses HTTP POST, these annotations would be useful:

* They document the expected behavior of servers.
* They allow client-side interceptors to adopt more aggressive retry policies.
* They allow gRPC-aware middleboxes to cache responses (though setting a TTL may be tricky).
* They allow other RPC protocols to serve the `Check` RPC using HTTP `GET`s.

Happy to open a PR if there's any interest!

**Comment by akshayjshah** [comment]
@markdroth Any chance you've got a moment to consider this? (Tagging you because you're the last person to have touched `health.proto`.)

**Comment by markdroth** [comment]
I don't think we want this, because we don't want health statuses being cached -- the whole point is to verify that the server is healthy, and if it goes unhealthy, we don't want the client still getting a cached signal that it was healthy.

**Comment by ejona86** [comment]
We don't respond with any caching headers, so they wouldn't be cached unless someone went out of their way to force caching in a proxy or using an interceptor to add the appropriate response headers.

**Comment by markdroth** [comment]
True, but I'm a little leery of making a change that might encourage doing something like that.  And it's really not clear to me that there's any other benefit here anyway.  I don't think we want retries of these RPCs -- if a server is too busy to serve a health check, it should be considered unhealthy.  And this is a gRPC-specific health check mechanism; I don't see a need to serve such requests via any other protocol.

**Comment by ejona86** [comment]
I'd expect there's _someone_ that wants this for GET to point an HTTP health checker at. But I would agree insofar someone should tell us their specific (legitimate) usecase and then we could add it.

**Comment by akshayjshah** [comment]
> True, but I'm a little leery of making a change that might encourage doing something like that.

I can understand some apprehension about seeming to encourage caching or retries. But zooming out a bit: why is gRPC more susceptible to these problems than other HTTP APIs? Nearly all HTTP health checks are `GET`s, and other systems aren't _unexpectedly_ beset by stale check results or fruitless retries. `GET`s give engineers more options when unusual situations come up. Marking `Check` side effect free offers those same options to engineers using gRPC.

From the discussion above, it seems like everyone agrees that `Check` is in fact intended to be free of side effects. If setting `idempotency_level` doesn't change the default behavior of any gRPC server, why not clearly spell out the expected behavior?

> I'd expect there's someone that wants this for GET to point an HTTP health checker at. But I would agree insofar someone should tell us their specific (legitimate) usecase and then we could add it.

🙋🏽 That's me! Some use cases from my previous work:

1. I'm building the distributed health checking portion of a service mesh control plane. I'd like a small set of probers to check the health of each service instance, aggregate those results in a control plane, and stream them to clients (either explicitly, or by filtering discovery results to just the instances willing to take traffic). This is implicitly caching the check results, of course. The probers also recheck each instance periodically, with new check results superseding old ones - so they're also acting as though all errors are retryable.
2. I'm building a decentralized membership system - something inspired by the SWIM paper, Hashicorp's Serf, or Uber's Ringpop. Nodes need to health check each other, but it's far too chatty to have every node check _every_ other node. Instead, nodes strike a balance between directly checking their peers and trusting secondhand information - which is just another form of caching. Because flapping nodes are expensive, I'd want some retries too - probably moving nodes between healthy, suspect, and unhealthy states.

In both cases, the current `Check` API is sufficient as long as I _assume_ that all implementations have `GET`-like semantics. In practice, I'd probably do that and consider any nonconforming implementation buggy. But that's exactly what the `idempotency_level` annotation codifies - that any side effect-ful implementation is incorrect.

**Comment by ejona86** [comment]
> the current Check API is sufficient as long as I assume that all implementations have GET-like semantics.

This is simply a documentation problem then. The documentation in the proto is pretty poor; it doesn't even say what Check does. [health-checking.md](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) discusses a lot more. But overall, the entire point of Check is for polling the health status... which means it has to be safe to poll.

If you want to suggest improvements to the documentation, that is easy. But that won't be in the form "provides GET-like semantics" as that is not a gRPC concept. More like "Gets the current health of the provided service."

**Comment by akshayjshah** [comment]
> If you want to suggest improvements to the documentation, that is easy. But that won't be in the form "provides GET-like semantics" as that is not a gRPC concept. More like "Gets the current health of the provided service."

Sure, happy to propose some changes. I'll probably borrow some language from the [gRPC proposal to support `GET`](https://github.com/grpc/grpc/issues/7945) that seems (from the outside, at least) to have prompted addition of the `idempotency_level` option.
