### ISSUE TITLE
weighted_target json name

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-proto#95]
All load balancer names are configured to have JSON names that have underscores. The one exception is `weighted_target`. It looks like it would be inferred to be `weightedTarget`. Is this intentional?

https://github.com/grpc/grpc-proto/blob/ec886024c2f7b7f597ba89d5b7d60c3f94627b17/grpc/service_config/service_config.proto#L356

Added [here](https://github.com/grpc/grpc-proto/commit/cf828d0e1155e5ea58b46d7184ee5596e03ddcb8)

@markdroth

**Comment by markdroth** [comment]
Yeah, it should be "weighted_target".  And actually, it should have an "_experimental" suffix right now.  And so should the priority policy.

I'll send a PR.
